name: Deploy CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    environment: allkindsofgains
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:

    - uses: actions/checkout@v3
    - name: Create and populate .env file
      env:
        DB_CLIENT: ${{ secrets.DB_CLIENT }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_URL: ${{ secrets.DB_URL }}
        PORT: ${{ secrets.PORT }}
        VUE_PORT: ${{ secrets.VUE_PORT }}
        ENV: ${{ secrets.ENV }}
        COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
        COOKIE_EXPIRATION: ${{ secrets.COOKIE_EXPIRATION }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PASSWORD_SALT: ${{ secrets.PASSWORD_SALT }}
        PINO_LOG_LEVEL: ${{ secrets.PINO_LOG_LEVEL }}
        DISCORD_ID: ${{ secrets.DISCORD_ID }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        EMAIL_AUTH_EMAIL: ${{ secrets.EMAIL_AUTH_EMAIL }}
        EMAIL_AUTH_PASS: ${{ secrets.EMAIL_AUTH_PASS }}    
        DOMAIN: ${{ secrets.DOMAIN }}   
      run: |
        cat <<EOF > .env
        DB_CLIENT="$DB_CLIENT"
        DB_PORT="$DB_PORT"
        DB_URL="$DB_URL"
        PORT="$PORT"
        VUE_PORT="$VUE_PORT"
        ENV="$ENV"
        COOKIE_SECRET="$COOKIE_SECRET"
        COOKIE_EXPIRATION="$COOKIE_EXPIRATION"
        JWT_SECRET="$JWT_SECRET"
        PASSWORD_SALT="$PASSWORD_SALT"
        DISCORD_ID="$DISCORD_ID"
        DISCORD_TOKEN="$DISCORD_TOKEN"
        DISCORD_URL="$DISCORD_URL"
        PINO_LOG_LEVEL="$PINO_LOG_LEVEL"
        EMAIL_HOST="$EMAIL_HOST"
        EMAIL_PORT="$EMAIL_PORT"
        EMAIL_AUTH_EMAIL="$EMAIL_AUTH_EMAIL"
        EMAIL_AUTH_PASS="$EMAIL_AUTH_PASS"  
        DOMAIN="$DOMAIN"             
        EOF
        echo "cat .env"
        cat .env
        echo "ls -a ${{ github.workspace }}"
        ls -a ${{ github.workspace }}
      shell: bash
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build
    - run: npm test
    - run: pm2 restart gains
